server:
  port: 8083

spring:
  application:
    name: search-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/ecom}

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

elasticsearch:
  uris: ${ELASTICSEARCH_URIS:http://localhost:9200}

recommendation:
  url: ${RECOMMENDATION_URL:http://localhost:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info
